# Generated by Django 5.2.4 on 2026-01-16 15:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendanceid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attendanceDetails', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='RMA',
            fields=[
                ('rmaid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rmaDetails', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SalesAndExpenses',
            fields=[
                ('salesid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('salesData', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('taslDetails', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobileNo', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(default='staff', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('workDescription', models.TextField(blank=True)),
                ('assignedAt', models.DateTimeField(auto_now_add=True)),
                ('workAssignedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
                ('workTask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.task')),
            ],
        ),
    ]
