# Generated by Django 5.2.4 on 2025-12-17 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_task_assigned_to_remove_task_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workDescription', models.TextField(blank=True)),
                ('assignedAt', models.DateTimeField(auto_now_add=True)),
                ('workAssignedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
                ('workTask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.task')),
            ],
        ),
    ]
