# Generated by Django 5.2.4 on 2025-12-19 05:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesAndExpenses',
            fields=[
                ('salesid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('salesData', models.JSONField(default=dict)),
            ],
        ),
    ]
